// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agents.proto

package io.grpc.aenetwork.agents;

public final class AgentsOuterClass {
  private AgentsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AgentDescriptionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AgentDescription)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string className = 2;</code>
     * @return The className.
     */
    java.lang.String getClassName();
    /**
     * <code>string className = 2;</code>
     * @return The bytes for className.
     */
    com.google.protobuf.ByteString
        getClassNameBytes();

    /**
     * <code>repeated float args = 3;</code>
     * @return A list containing the args.
     */
    java.util.List<java.lang.Float> getArgsList();
    /**
     * <code>repeated float args = 3;</code>
     * @return The count of args.
     */
    int getArgsCount();
    /**
     * <code>repeated float args = 3;</code>
     * @param index The index of the element to return.
     * @return The args at the given index.
     */
    float getArgs(int index);
  }
  /**
   * Protobuf type {@code AgentDescription}
   */
  public static final class AgentDescription extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AgentDescription)
      AgentDescriptionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AgentDescription.newBuilder() to construct.
    private AgentDescription(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AgentDescription() {
      name_ = "";
      className_ = "";
      args_ = emptyFloatList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AgentDescription();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AgentDescription(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              className_ = s;
              break;
            }
            case 29: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                args_ = newFloatList();
                mutable_bitField0_ |= 0x00000001;
              }
              args_.addFloat(input.readFloat());
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                args_ = newFloatList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                args_.addFloat(input.readFloat());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          args_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.aenetwork.agents.AgentsOuterClass.internal_static_AgentDescription_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.aenetwork.agents.AgentsOuterClass.internal_static_AgentDescription_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription.class, io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLASSNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object className_;
    /**
     * <code>string className = 2;</code>
     * @return The className.
     */
    @java.lang.Override
    public java.lang.String getClassName() {
      java.lang.Object ref = className_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        className_ = s;
        return s;
      }
    }
    /**
     * <code>string className = 2;</code>
     * @return The bytes for className.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getClassNameBytes() {
      java.lang.Object ref = className_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        className_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ARGS_FIELD_NUMBER = 3;
    private com.google.protobuf.Internal.FloatList args_;
    /**
     * <code>repeated float args = 3;</code>
     * @return A list containing the args.
     */
    @java.lang.Override
    public java.util.List<java.lang.Float>
        getArgsList() {
      return args_;
    }
    /**
     * <code>repeated float args = 3;</code>
     * @return The count of args.
     */
    public int getArgsCount() {
      return args_.size();
    }
    /**
     * <code>repeated float args = 3;</code>
     * @param index The index of the element to return.
     * @return The args at the given index.
     */
    public float getArgs(int index) {
      return args_.getFloat(index);
    }
    private int argsMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getClassNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, className_);
      }
      if (getArgsList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(argsMemoizedSerializedSize);
      }
      for (int i = 0; i < args_.size(); i++) {
        output.writeFloatNoTag(args_.getFloat(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getClassNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, className_);
      }
      {
        int dataSize = 0;
        dataSize = 4 * getArgsList().size();
        size += dataSize;
        if (!getArgsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        argsMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription)) {
        return super.equals(obj);
      }
      io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription other = (io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getClassName()
          .equals(other.getClassName())) return false;
      if (!getArgsList()
          .equals(other.getArgsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + CLASSNAME_FIELD_NUMBER;
      hash = (53 * hash) + getClassName().hashCode();
      if (getArgsCount() > 0) {
        hash = (37 * hash) + ARGS_FIELD_NUMBER;
        hash = (53 * hash) + getArgsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AgentDescription}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AgentDescription)
        io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescriptionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.grpc.aenetwork.agents.AgentsOuterClass.internal_static_AgentDescription_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.grpc.aenetwork.agents.AgentsOuterClass.internal_static_AgentDescription_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription.class, io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription.Builder.class);
      }

      // Construct using io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        className_ = "";

        args_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.grpc.aenetwork.agents.AgentsOuterClass.internal_static_AgentDescription_descriptor;
      }

      @java.lang.Override
      public io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription getDefaultInstanceForType() {
        return io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription.getDefaultInstance();
      }

      @java.lang.Override
      public io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription build() {
        io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription buildPartial() {
        io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription result = new io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription(this);
        int from_bitField0_ = bitField0_;
        result.name_ = name_;
        result.className_ = className_;
        if (((bitField0_ & 0x00000001) != 0)) {
          args_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.args_ = args_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription) {
          return mergeFrom((io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription other) {
        if (other == io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getClassName().isEmpty()) {
          className_ = other.className_;
          onChanged();
        }
        if (!other.args_.isEmpty()) {
          if (args_.isEmpty()) {
            args_ = other.args_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureArgsIsMutable();
            args_.addAll(other.args_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object className_ = "";
      /**
       * <code>string className = 2;</code>
       * @return The className.
       */
      public java.lang.String getClassName() {
        java.lang.Object ref = className_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          className_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string className = 2;</code>
       * @return The bytes for className.
       */
      public com.google.protobuf.ByteString
          getClassNameBytes() {
        java.lang.Object ref = className_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          className_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string className = 2;</code>
       * @param value The className to set.
       * @return This builder for chaining.
       */
      public Builder setClassName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        className_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string className = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearClassName() {
        
        className_ = getDefaultInstance().getClassName();
        onChanged();
        return this;
      }
      /**
       * <code>string className = 2;</code>
       * @param value The bytes for className to set.
       * @return This builder for chaining.
       */
      public Builder setClassNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        className_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.FloatList args_ = emptyFloatList();
      private void ensureArgsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          args_ = mutableCopy(args_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated float args = 3;</code>
       * @return A list containing the args.
       */
      public java.util.List<java.lang.Float>
          getArgsList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(args_) : args_;
      }
      /**
       * <code>repeated float args = 3;</code>
       * @return The count of args.
       */
      public int getArgsCount() {
        return args_.size();
      }
      /**
       * <code>repeated float args = 3;</code>
       * @param index The index of the element to return.
       * @return The args at the given index.
       */
      public float getArgs(int index) {
        return args_.getFloat(index);
      }
      /**
       * <code>repeated float args = 3;</code>
       * @param index The index to set the value at.
       * @param value The args to set.
       * @return This builder for chaining.
       */
      public Builder setArgs(
          int index, float value) {
        ensureArgsIsMutable();
        args_.setFloat(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float args = 3;</code>
       * @param value The args to add.
       * @return This builder for chaining.
       */
      public Builder addArgs(float value) {
        ensureArgsIsMutable();
        args_.addFloat(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float args = 3;</code>
       * @param values The args to add.
       * @return This builder for chaining.
       */
      public Builder addAllArgs(
          java.lang.Iterable<? extends java.lang.Float> values) {
        ensureArgsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, args_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated float args = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearArgs() {
        args_ = emptyFloatList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AgentDescription)
    }

    // @@protoc_insertion_point(class_scope:AgentDescription)
    private static final io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription();
    }

    public static io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AgentDescription>
        PARSER = new com.google.protobuf.AbstractParser<AgentDescription>() {
      @java.lang.Override
      public AgentDescription parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AgentDescription(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AgentDescription> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AgentDescription> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CreateAgentsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CreateAgentsRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .AgentDescription agents = 1;</code>
     */
    java.util.List<io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription> 
        getAgentsList();
    /**
     * <code>repeated .AgentDescription agents = 1;</code>
     */
    io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription getAgents(int index);
    /**
     * <code>repeated .AgentDescription agents = 1;</code>
     */
    int getAgentsCount();
    /**
     * <code>repeated .AgentDescription agents = 1;</code>
     */
    java.util.List<? extends io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescriptionOrBuilder> 
        getAgentsOrBuilderList();
    /**
     * <code>repeated .AgentDescription agents = 1;</code>
     */
    io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescriptionOrBuilder getAgentsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code CreateAgentsRequest}
   */
  public static final class CreateAgentsRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CreateAgentsRequest)
      CreateAgentsRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CreateAgentsRequest.newBuilder() to construct.
    private CreateAgentsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CreateAgentsRequest() {
      agents_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CreateAgentsRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CreateAgentsRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                agents_ = new java.util.ArrayList<io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription>();
                mutable_bitField0_ |= 0x00000001;
              }
              agents_.add(
                  input.readMessage(io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          agents_ = java.util.Collections.unmodifiableList(agents_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.aenetwork.agents.AgentsOuterClass.internal_static_CreateAgentsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.aenetwork.agents.AgentsOuterClass.internal_static_CreateAgentsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest.class, io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest.Builder.class);
    }

    public static final int AGENTS_FIELD_NUMBER = 1;
    private java.util.List<io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription> agents_;
    /**
     * <code>repeated .AgentDescription agents = 1;</code>
     */
    @java.lang.Override
    public java.util.List<io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription> getAgentsList() {
      return agents_;
    }
    /**
     * <code>repeated .AgentDescription agents = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescriptionOrBuilder> 
        getAgentsOrBuilderList() {
      return agents_;
    }
    /**
     * <code>repeated .AgentDescription agents = 1;</code>
     */
    @java.lang.Override
    public int getAgentsCount() {
      return agents_.size();
    }
    /**
     * <code>repeated .AgentDescription agents = 1;</code>
     */
    @java.lang.Override
    public io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription getAgents(int index) {
      return agents_.get(index);
    }
    /**
     * <code>repeated .AgentDescription agents = 1;</code>
     */
    @java.lang.Override
    public io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescriptionOrBuilder getAgentsOrBuilder(
        int index) {
      return agents_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < agents_.size(); i++) {
        output.writeMessage(1, agents_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < agents_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, agents_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest)) {
        return super.equals(obj);
      }
      io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest other = (io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest) obj;

      if (!getAgentsList()
          .equals(other.getAgentsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getAgentsCount() > 0) {
        hash = (37 * hash) + AGENTS_FIELD_NUMBER;
        hash = (53 * hash) + getAgentsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CreateAgentsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CreateAgentsRequest)
        io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.grpc.aenetwork.agents.AgentsOuterClass.internal_static_CreateAgentsRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.grpc.aenetwork.agents.AgentsOuterClass.internal_static_CreateAgentsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest.class, io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest.Builder.class);
      }

      // Construct using io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAgentsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (agentsBuilder_ == null) {
          agents_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          agentsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.grpc.aenetwork.agents.AgentsOuterClass.internal_static_CreateAgentsRequest_descriptor;
      }

      @java.lang.Override
      public io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest getDefaultInstanceForType() {
        return io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest.getDefaultInstance();
      }

      @java.lang.Override
      public io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest build() {
        io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest buildPartial() {
        io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest result = new io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest(this);
        int from_bitField0_ = bitField0_;
        if (agentsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            agents_ = java.util.Collections.unmodifiableList(agents_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.agents_ = agents_;
        } else {
          result.agents_ = agentsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest) {
          return mergeFrom((io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest other) {
        if (other == io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest.getDefaultInstance()) return this;
        if (agentsBuilder_ == null) {
          if (!other.agents_.isEmpty()) {
            if (agents_.isEmpty()) {
              agents_ = other.agents_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAgentsIsMutable();
              agents_.addAll(other.agents_);
            }
            onChanged();
          }
        } else {
          if (!other.agents_.isEmpty()) {
            if (agentsBuilder_.isEmpty()) {
              agentsBuilder_.dispose();
              agentsBuilder_ = null;
              agents_ = other.agents_;
              bitField0_ = (bitField0_ & ~0x00000001);
              agentsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAgentsFieldBuilder() : null;
            } else {
              agentsBuilder_.addAllMessages(other.agents_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription> agents_ =
        java.util.Collections.emptyList();
      private void ensureAgentsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          agents_ = new java.util.ArrayList<io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription>(agents_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription, io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription.Builder, io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescriptionOrBuilder> agentsBuilder_;

      /**
       * <code>repeated .AgentDescription agents = 1;</code>
       */
      public java.util.List<io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription> getAgentsList() {
        if (agentsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(agents_);
        } else {
          return agentsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .AgentDescription agents = 1;</code>
       */
      public int getAgentsCount() {
        if (agentsBuilder_ == null) {
          return agents_.size();
        } else {
          return agentsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .AgentDescription agents = 1;</code>
       */
      public io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription getAgents(int index) {
        if (agentsBuilder_ == null) {
          return agents_.get(index);
        } else {
          return agentsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .AgentDescription agents = 1;</code>
       */
      public Builder setAgents(
          int index, io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription value) {
        if (agentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAgentsIsMutable();
          agents_.set(index, value);
          onChanged();
        } else {
          agentsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .AgentDescription agents = 1;</code>
       */
      public Builder setAgents(
          int index, io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription.Builder builderForValue) {
        if (agentsBuilder_ == null) {
          ensureAgentsIsMutable();
          agents_.set(index, builderForValue.build());
          onChanged();
        } else {
          agentsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AgentDescription agents = 1;</code>
       */
      public Builder addAgents(io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription value) {
        if (agentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAgentsIsMutable();
          agents_.add(value);
          onChanged();
        } else {
          agentsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .AgentDescription agents = 1;</code>
       */
      public Builder addAgents(
          int index, io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription value) {
        if (agentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAgentsIsMutable();
          agents_.add(index, value);
          onChanged();
        } else {
          agentsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .AgentDescription agents = 1;</code>
       */
      public Builder addAgents(
          io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription.Builder builderForValue) {
        if (agentsBuilder_ == null) {
          ensureAgentsIsMutable();
          agents_.add(builderForValue.build());
          onChanged();
        } else {
          agentsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AgentDescription agents = 1;</code>
       */
      public Builder addAgents(
          int index, io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription.Builder builderForValue) {
        if (agentsBuilder_ == null) {
          ensureAgentsIsMutable();
          agents_.add(index, builderForValue.build());
          onChanged();
        } else {
          agentsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AgentDescription agents = 1;</code>
       */
      public Builder addAllAgents(
          java.lang.Iterable<? extends io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription> values) {
        if (agentsBuilder_ == null) {
          ensureAgentsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, agents_);
          onChanged();
        } else {
          agentsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .AgentDescription agents = 1;</code>
       */
      public Builder clearAgents() {
        if (agentsBuilder_ == null) {
          agents_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          agentsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .AgentDescription agents = 1;</code>
       */
      public Builder removeAgents(int index) {
        if (agentsBuilder_ == null) {
          ensureAgentsIsMutable();
          agents_.remove(index);
          onChanged();
        } else {
          agentsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .AgentDescription agents = 1;</code>
       */
      public io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription.Builder getAgentsBuilder(
          int index) {
        return getAgentsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .AgentDescription agents = 1;</code>
       */
      public io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescriptionOrBuilder getAgentsOrBuilder(
          int index) {
        if (agentsBuilder_ == null) {
          return agents_.get(index);  } else {
          return agentsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .AgentDescription agents = 1;</code>
       */
      public java.util.List<? extends io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescriptionOrBuilder> 
           getAgentsOrBuilderList() {
        if (agentsBuilder_ != null) {
          return agentsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(agents_);
        }
      }
      /**
       * <code>repeated .AgentDescription agents = 1;</code>
       */
      public io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription.Builder addAgentsBuilder() {
        return getAgentsFieldBuilder().addBuilder(
            io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription.getDefaultInstance());
      }
      /**
       * <code>repeated .AgentDescription agents = 1;</code>
       */
      public io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription.Builder addAgentsBuilder(
          int index) {
        return getAgentsFieldBuilder().addBuilder(
            index, io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription.getDefaultInstance());
      }
      /**
       * <code>repeated .AgentDescription agents = 1;</code>
       */
      public java.util.List<io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription.Builder> 
           getAgentsBuilderList() {
        return getAgentsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription, io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription.Builder, io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescriptionOrBuilder> 
          getAgentsFieldBuilder() {
        if (agentsBuilder_ == null) {
          agentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription, io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescription.Builder, io.grpc.aenetwork.agents.AgentsOuterClass.AgentDescriptionOrBuilder>(
                  agents_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          agents_ = null;
        }
        return agentsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CreateAgentsRequest)
    }

    // @@protoc_insertion_point(class_scope:CreateAgentsRequest)
    private static final io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest();
    }

    public static io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreateAgentsRequest>
        PARSER = new com.google.protobuf.AbstractParser<CreateAgentsRequest>() {
      @java.lang.Override
      public CreateAgentsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreateAgentsRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CreateAgentsRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreateAgentsRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CreateAgentsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CreateAgentsResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool ok = 1;</code>
     * @return The ok.
     */
    boolean getOk();
  }
  /**
   * Protobuf type {@code CreateAgentsResponse}
   */
  public static final class CreateAgentsResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CreateAgentsResponse)
      CreateAgentsResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CreateAgentsResponse.newBuilder() to construct.
    private CreateAgentsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CreateAgentsResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CreateAgentsResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CreateAgentsResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              ok_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.aenetwork.agents.AgentsOuterClass.internal_static_CreateAgentsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.aenetwork.agents.AgentsOuterClass.internal_static_CreateAgentsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse.class, io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse.Builder.class);
    }

    public static final int OK_FIELD_NUMBER = 1;
    private boolean ok_;
    /**
     * <code>bool ok = 1;</code>
     * @return The ok.
     */
    @java.lang.Override
    public boolean getOk() {
      return ok_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (ok_ != false) {
        output.writeBool(1, ok_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (ok_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, ok_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse)) {
        return super.equals(obj);
      }
      io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse other = (io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse) obj;

      if (getOk()
          != other.getOk()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + OK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getOk());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CreateAgentsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CreateAgentsResponse)
        io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.grpc.aenetwork.agents.AgentsOuterClass.internal_static_CreateAgentsResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.grpc.aenetwork.agents.AgentsOuterClass.internal_static_CreateAgentsResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse.class, io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse.Builder.class);
      }

      // Construct using io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ok_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.grpc.aenetwork.agents.AgentsOuterClass.internal_static_CreateAgentsResponse_descriptor;
      }

      @java.lang.Override
      public io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse getDefaultInstanceForType() {
        return io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse.getDefaultInstance();
      }

      @java.lang.Override
      public io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse build() {
        io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse buildPartial() {
        io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse result = new io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse(this);
        result.ok_ = ok_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse) {
          return mergeFrom((io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse other) {
        if (other == io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse.getDefaultInstance()) return this;
        if (other.getOk() != false) {
          setOk(other.getOk());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean ok_ ;
      /**
       * <code>bool ok = 1;</code>
       * @return The ok.
       */
      @java.lang.Override
      public boolean getOk() {
        return ok_;
      }
      /**
       * <code>bool ok = 1;</code>
       * @param value The ok to set.
       * @return This builder for chaining.
       */
      public Builder setOk(boolean value) {
        
        ok_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool ok = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOk() {
        
        ok_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:CreateAgentsResponse)
    }

    // @@protoc_insertion_point(class_scope:CreateAgentsResponse)
    private static final io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse();
    }

    public static io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreateAgentsResponse>
        PARSER = new com.google.protobuf.AbstractParser<CreateAgentsResponse>() {
      @java.lang.Override
      public CreateAgentsResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreateAgentsResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CreateAgentsResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreateAgentsResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.grpc.aenetwork.agents.AgentsOuterClass.CreateAgentsResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AgentDescription_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AgentDescription_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateAgentsRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateAgentsRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateAgentsResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateAgentsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014agents.proto\"A\n\020AgentDescription\022\014\n\004na" +
      "me\030\001 \001(\t\022\021\n\tclassName\030\002 \001(\t\022\014\n\004args\030\003 \003(" +
      "\002\"8\n\023CreateAgentsRequest\022!\n\006agents\030\001 \003(\013" +
      "2\021.AgentDescription\"\"\n\024CreateAgentsRespo" +
      "nse\022\n\n\002ok\030\001 \001(\0102E\n\006Agents\022;\n\014CreateAgent" +
      "s\022\024.CreateAgentsRequest\032\025.CreateAgentsRe" +
      "sponseB\032\n\030io.grpc.aenetwork.agentsb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_AgentDescription_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AgentDescription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AgentDescription_descriptor,
        new java.lang.String[] { "Name", "ClassName", "Args", });
    internal_static_CreateAgentsRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CreateAgentsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateAgentsRequest_descriptor,
        new java.lang.String[] { "Agents", });
    internal_static_CreateAgentsResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CreateAgentsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateAgentsResponse_descriptor,
        new java.lang.String[] { "Ok", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
