import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Добро пожаловать в <a href="https://aenetwork.vercel.app/app">AENet!</a>
        </h1>

        <p className={styles.description}>
          Начните с посещения{' '}
          <code className={styles.code}>aenetwork.vercel.app/app</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Документация &rarr;</h2>
            <p>Узнайте всю необходимую информацию о возможностях AENet и функционального API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Изучите &rarr;</h2>
            <p>Изучите основные принципы работы с AENet и познакомьтесь с рабочей средой.</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Примеры &rarr;</h2>
            <p>Посмотрите на примеры организации мультиагентного рынка в АЭК.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Разработайте &rarr;</h2>
            <p>
              Разработайте и протестируйте поведение своего первого агента в AENet.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Работает в середе {' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
